[project]
name = "mng-compiler"
version = "1.0.0"
description = "Compiler for M&G turing machines"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llvmlite>=0.45.1",
    "typer>=0.20.0",
]
